#! /bin/bash

# env variable
export BUDGRRC=./.budgrrc

# remove everything from testdata dir
rm testdata/*

# building binary
cargo build

# create some mock data
./target/debug/budgr a 20231213 "Test note for operation 1 to be deleted" 5000 --id 1
./target/debug/budgr a 20231213 "Test note for operation 2 to be deleted" 5000 --id 2
./target/debug/budgr a 20231213 "Test note for operation 3 to be deleted" 5000 --id 3
./target/debug/budgr d
./target/debug/budgr a 20240101 "Test note for operation 1" 5000 --id 4
./target/debug/budgr a 20240102 "Test note for operation 2" 6000 --id 5
./target/debug/budgr a 20240103 "Test note for operation 3" 7000 --id 6
./target/debug/budgr a 20240104 "Test note for operation 4" 8000 -a "BNP Paribas" --id 7
./target/debug/budgr a 20240105 "Test note for operation 5" 9000 -a "BNP Paribas" -g "Gifts" --id 8
./target/debug/budgr a 20240106 "Test note for operation 6" 4000 -p "need" --id 9
./target/debug/budgr a 20240107 "Test note for operation 7" 9000 -p "income" --id 10

./target/debug/budgr a 20240108 "Test note for operation 8" 9000 -a "UBS" -p "need"  --id 11
./target/debug/budgr a 20240109 "Test note for operation 9" 9000 -p "yearly-need"  --id 12
./target/debug/budgr a 20240110 "Test note for operation 10" 9000 -p "want" --id 13
./target/debug/budgr a 20240111 "Test note for operation 11" 9000 -p "yearly-want" --id 14
./target/debug/budgr a 20240112 "Test note for operation 12" 9000 -p "goal" --id 15
./target/debug/budgr a 20240113 "Test note for operation 13" 9000 -p "income" --id 16

# list deleted operations
./target/debug/budgr -d l -o pretty
./target/debug/budgr l -o pretty
