#! /bin/bash

# env variable
export BUDGRRC=./.budgrrc

# remove everything from testdata dir
rm testdata/*

# create some mock data
cargo run -- add 20231213 "Test note for operation 1 to be deleted" 5000 --id 1
cargo run -- add 20231213 "Test note for operation 2 to be deleted" 5000 --id 2
cargo run -- add 20231213 "Test note for operation 3 to be deleted" 5000 --id 3
cargo run -- delete
cargo run -- add 20240101 "Test note for operation 1" 5000 --id 4
cargo run -- add 20240102 "Test note for operation 2" 6000 --id 5
cargo run -- add 20240103 "Test note for operation 3" 7000 --id 6
cargo run -- add 20240104 "Test note for operation 4" 8000 -a "BNP Paribas" --id 7
cargo run -- add 20240105 "Test note for operation 5" 9000 -g "Gifts" --id 8
cargo run -- add 20240106 "Test note for operation 6" 4000 -p "need" --id 9

# list deleted operations
cargo run -- -d list -o pretty
cargo run -- list -o pretty
